users: list = [
    {'name': 'Karolina', 'posts': 1, 'city': 'Warszawa'},
    {'name': 'Dominik', 'posts': 3, 'city': 'Poznań'},
    {'name': 'Szymon z wąsem', 'posts': 5, 'city': 'Toruń'},
    {'name': 'Szymon', 'posts': 7, 'city': 'Łódź'},
    {'name': 'Patryk', 'posts': 9, 'city': 'Kielce'},
    {'name': 'Żerom', 'posts': 11, 'city': 'Katowice'},
    {'name': 'Julia', 'posts': 15, 'city': 'Wrocław'},
    {'name': 'Ola', 'posts': 11, 'city': 'Radom'},
    {'name': 'Patrycja', 'posts': 20, 'city': 'Lublin'},
    {'name': 'Patrycja', 'posts': 5, 'city': 'Mińsk Mazowiecki'},
    {'name': 'Patrycja', 'posts': 8, 'city': 'Bydgoszcz'},
    {'name': 'Amelia', 'posts': 6, 'city': 'Toruń'},
    {'name': 'Kinga', 'posts': 2, 'city': 'Iława'},
    {'name': 'Dominik', 'posts': 3, 'city': 'Kraków'},
    {'name': 'Michał', 'posts': 1, 'city': 'Gdańsk'},
]